var ran = new Date().getTime();
document.write('<div id="ad-container'+ran+'">');
var adTechAdPlayer = new AdPlayer('ADTECH-AdServer_OUTER', 'ad-container'+ran);
adTechAdPlayer.addPrivacyInfo('ADTECH-AdServer_OUTER', 'Opt out of this campaign', 'http://www.adtech.com/adserver');
adTechAdPlayer.addEventListener(AdEvent.INIT, adtechPlayerInit);
adTechAdPlayer.addEventListener(AdEvent.PRIVACY_OPEN, adtechPlayerPrivacyOpen);
adTechAdPlayer.addEventListener(AdEvent.PRIVACY_CLOSE, adtechPlayerPrivacyClose);
adTechAdPlayer.addEventListener(AdEvent.PRIVACY_CLICK, adtechPlayerInfoClick);        
document.write('<scr'+'ipt language="javascript1.1" src="http://adserver.adtechus.com/addyn/3.0/5071/2132472/0/170/ADTECH;loc=100;target=_blank;key=key1+key2+key3+key4;grp=[group];misc='+new Date().getTime()+'"></scri'+'pt>');
document.write('<scr'+'ipt language="javascript1.1" src="demo/example2.js?misc='+new Date().getTime()+'"></scri'+'pt>');
document.write('</div>');